import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  mainSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'getting-started',
        },
      ],
    },
    {
      type: 'category',
      label: 'Specification Reference',
      collapsible: true,
      collapsed: false,
      items: [
        'reference/overview',
        'reference/connector-schema',
        'reference/workflow-schema',
        'reference/agent-schema',
        'reference/workflow-logic-nodes',
        'reference/execution-backends',
        'reference/execution-modes',
        'reference/security',
        'reference/registry-protocol',
        'reference/registry-taxonomy',
        'reference/sdk-contract',
      ],
    },
    {
      type: 'category',
      label: 'Examples',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'examples',
        },
      ],
    },
    'contributing',
    'changelog',
  ],
};

export default sidebars;
